-- 放开所有表的 RLS 限制
ALTER TABLE kocs DISABLE ROW LEVEL SECURITY;
ALTER TABLE point_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE redemption_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE reward_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE score_imports DISABLE ROW LEVEL SECURITY;
